# ローカル開発環境のみに使用する
version: '3'
services:
  app:
    image: openjdk:8-jdk-alpine
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    working_dir: /app
    command: ./gradlew bootRun
    networks:
      - web
  db:
    restart: always
    image: mysql:5.7.24
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      MYSQL_DATABASE: sampledb
    volumes:
    - ./db/data:/var/lib/mysql
    networks:
      - web

networks:
  web: